// <auto-generated />
using System;
using EFGetStarted;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(HPContext))]
    [Migration("20200424155939_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("EFGetStarted.Casos", b =>
                {
                    b.Property<int>("CasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicosMatricula")
                        .HasColumnType("INTEGER");

                    b.HasKey("CasoId");

                    b.HasIndex("MedicosMatricula");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("EFGetStarted.Consultas", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionSintomas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicosMatricula")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PacientesPacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsultaId");

                    b.HasIndex("MedicosMatricula");

                    b.HasIndex("PacientesPacienteId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("EFGetStarted.Medicos", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("EFGetStarted.Pacientes", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<int>("CasosForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dni")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.HasIndex("CasosForeignKey")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("EFGetStarted.Pruebas", b =>
                {
                    b.Property<int>("PruebaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CasosCasoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Resultado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PruebaId");

                    b.HasIndex("CasosCasoId");

                    b.ToTable("Pruebas");
                });

            modelBuilder.Entity("EFGetStarted.Casos", b =>
                {
                    b.HasOne("EFGetStarted.Medicos", "Medicos")
                        .WithMany("Casos")
                        .HasForeignKey("MedicosMatricula");
                });

            modelBuilder.Entity("EFGetStarted.Consultas", b =>
                {
                    b.HasOne("EFGetStarted.Medicos", "Medicos")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicosMatricula");

                    b.HasOne("EFGetStarted.Pacientes", "Pacientes")
                        .WithMany("Consultas")
                        .HasForeignKey("PacientesPacienteId");
                });

            modelBuilder.Entity("EFGetStarted.Pacientes", b =>
                {
                    b.HasOne("EFGetStarted.Casos", "Casos")
                        .WithOne("Pacientes")
                        .HasForeignKey("EFGetStarted.Pacientes", "CasosForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFGetStarted.Pruebas", b =>
                {
                    b.HasOne("EFGetStarted.Casos", "Casos")
                        .WithMany("Pruebas")
                        .HasForeignKey("CasosCasoId");
                });
#pragma warning restore 612, 618
        }
    }
}
